---
driver:
  name: vagrant

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_chef_for_busser: false
  require_ruby_for_busser: true
  ansible_verbosity: 3
  ansible_verbose: true
  requirements_path: requirements-test.yml
 
platforms:
  - name: ubuntu-14.04

suites:
  - name: default
  - name: liferayMysql
  - name: liferayDebugEnabled

# Fix for: https://github.com/neillturner/kitchen-ansible/issues/66
verifier:
  ruby_bindir: '/usr/bin'
